import styled from "styled-components";
const SystemPromptTextArea = styled.textarea`
  background-color: rgba(60, 60, 60, 0.6);
  color: white;
  padding: 4px;
  margin: 0 1px;
  width: 99%;
  max-width: 99%;
  box-sizing: border-box;
  flex-grow: 1;
  outline: 0;
  border-top: 0 none;
  border-right: 0 none;
  border-bottom: 0 none;
  border-left: 0 none;
  overflow-x: hidden;
  user-select: none;
  border: 1px solid lightblue;
  border-radius: 10px;
  font-weight: 500;
  font-size: 0.8em;
  overflow-wrap: anywhere;
  word-break: keep-all;
  text-align: justify;
  min-height: 30svh;
`;
export default SystemPromptTextArea;
